version: '3.1'

services:
  web:
    container_name: ds-nginx-cache
    image: dalso/ds-nginx:1.25.3-alpine
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - 85:80
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/log/nginx:/var/log/nginx
